### ISSUE TITLE
options to use bfile instead of impute2 for SKAT?

### ISSUE THREAD

**Issue by gpcr** [pgxcentre/genipe#39]
I need to run SKAT using plink bfile directly without imputation any options for the same?
Thanks

**Comment by lemieuxl** [comment]
`genipe` is an imputation pipeline. Hence, we only provide tools to work with IMPUTE2 files.
`SKAT` actually works directly with binary Plink files (see SKAT's [vignette](https://cran.r-project.org/web/packages/SKAT/vignettes/SKAT.pdf), section 2.7).
