### ISSUE TITLE
genipe-tutorial fails when broken link

### ISSUE THREAD

**Issue by klevdiamanti** [pgxcentre/genipe#40]
Hi,
when running genipe tutorial it failed when it tried to download PLINK from http://pngu.mgh.harvard.edu/~purcell/plink/dist/plink-1.07-x86_64.zip because the link is broken. Is there any way to skip this or fix it or add a custom link (e.g. https://www.cog-genomics.org/static/bin/plink/plink1_linux_x86_64.zip)?
Thanks,
Klev

**Comment by lemieuxl** [comment]
Thank you, I forgot that the original link to download Plink wasn't working anymore. I'll modify the script accordingly.

In the meantime, a quick work around would be to execute the script (as you just did), wait that it crashes and then copy the Plink binary you manually downloaded into the tutorial directory (usually `$HOME/genipe_tutorial`).

**Comment by lemieuxl** [comment]
The `genipe-tutorial` was updated in version 1.3.3. It now uses binaries from the system path (if available). Otherwise, Plink is downloaded from [http://zzz.bwh.harvard.edu/plink/download.shtml](http://zzz.bwh.harvard.edu/plink/download.shtml) (the new website).
