### ISSUE TITLE
Error in file genipe/pipeline/cli.py

### ISSUE THREAD

**Issue by dlippold** [pgxcentre/genipe#42]
After I installed genipe (on a fully updated Fedora 25 system) as described in the documentation and after correcting one error (see below) I executed the test and get an error message.

In detail I did the following as root:

`dnf install python3 python3-devel python3-numpy python3-jinja2 python3-pandas python3-setuptools`

And then I did the following as a user:

`pyvenv $HOME/genipe_pyvenv`
`source $HOME/genipe_pyvenv/bin/activate`
`pip install genipe`
`pip install pyfaidx`
`deactivate`

Because of another error message (see ticket #41) I then replaced the character 'd' in line 247 of the file genipe/tools/imputed_stats.py by the  character 'f'.

Then I did:

`source $HOME/genipe_pyvenv/bin/activate`
`python`
`import genipe`
`genipe.test()`

After that I get the following error message:

>ERROR: test_gather_maf_stats (genipe.tests.test_main_pipeline.TestMainPipeline)
>Tests the 'gather_maf_stats' function.
>----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "/home/user/genipe_pyvenv/lib64/python3.5/site-packages/genipe/tests/test_main_pipeline.py", line 588, in test_gather_maf_stats
>    o_dir=self.output_dir.name,
>  File "/home/user/genipe_pyvenv/lib64/python3.5/site-packages/genipe/pipeline/cli.py", line 2480, in gather_maf_stats
>    raise GenipeError("something went wrong")
>genipe.error.GenipeError: something went wrong

The output of the command `source $HOME/genipe_pyvenv/bin/activate; python --version; deactivate` is: Python 3.5.4

**Comment by lemieuxl** [comment]
The failed test looks like it's related to pandas version 0.21.

```console
$ pip list
Package         Version
--------------- -------
genipe          1.3.3  
Jinja2          2.10   
MarkupSafe      1.0    
numpy           1.13.3 
pandas          0.21.0 
pip             9.0.1  
pyfaidx         0.5.1  
python-dateutil 2.6.1  
pytz            2017.3 
setuptools      36.6.0 
six             1.11.0 
$ python -m unittest genipe.tests.test_main_pipeline.TestMainPipeline.test_gather_maf_stats 
E
======================================================================
ERROR: test_gather_maf_stats (genipe.tests.test_main_pipeline.TestMainPipeline)
Tests the 'gather_maf_stats' function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lemieuxl/genipe_pyvenv/lib64/python3.6/site-packages/genipe/tests/test_main_pipeline.py", line 588, in test_gather_maf_stats
    o_dir=self.output_dir.name,
  File "/home/lemieuxl/genipe_pyvenv/lib64/python3.6/site-packages/genipe/pipeline/cli.py", line 2480, in gather_maf_stats
    raise GenipeError("something went wrong")
genipe.error.GenipeError: something went wrong

----------------------------------------------------------------------
Ran 1 test in 0.177s

FAILED (errors=1)
```

If you downgrade to pandas version 0.20, the test should pass.

```console
$ pip list
Package         Version
--------------- -------
genipe          1.3.3  
Jinja2          2.10   
MarkupSafe      1.0    
numpy           1.13.3 
pandas          0.20.0 
pip             9.0.1  
pyfaidx         0.5.1  
python-dateutil 2.6.1  
pytz            2017.3 
setuptools      36.6.0 
six             1.11.0 
$ python -m unittest genipe.tests.test_main_pipeline.TestMainPipeline.test_gather_maf_stats 
.
----------------------------------------------------------------------
Ran 1 test in 0.441s

OK
```

I will fix this in a future release, but, for now, I suggest downgrading to pandas version 0.20.

**Comment by dlippold** [comment]
Yes, I have the same result. After installation of two RPM packages and downgrading pandas (see comment for #41) there was no error anymore.
