### ISSUE TITLE
Define an option for the directory with the IMPUTE2 reference files

### ISSUE THREAD

**Issue by dlippold** [pgxcentre/genipe#47]
It seems to me that the paths of the IMPUTE2 reference files, in particular those many for chromosome X, have to be specified individually by options of `genipe-launcher` (e.g. by `--hap-nonPAR` and `--legend-nonPAR`). But all these files are contained in the tar files `1000GP_Phase3.tgz` and `1000GP_Phase3_chrX.tgz` and are extracted into the directory `1000GP_Phase3` by default.

Therefore I want to suggest that there should be a option `--impute2-ref-dir` (or something similar) to specify the directory with all IMPUTE2 reference files (for the autosomes and for the allosomes).

**Comment by lemieuxl** [comment]
We want *genipe* to be as general as possible (*i.e.* it should work with any reference datasets, past and future).

There is no standard for IMPUTE2 reference file naming. For example, 1000G phase 1 has two datasets with two different naming templates (`ALL.chr{chrom}.integrated_phase1_v3.20101123.snps_indels_svs.genotypes.nosing.haplotypes.gz` vs `ALL.chr{chrom}.integrated_phase1_v3.20101123.snps_indels_svs.genotypes.nomono.haplotypes.gz`). These templates are, in turn, different from the 1000G phase 3 naming template (*e.g.* `1000GP_Phase3_chr{chrom}.hap.gz`).

Hence, we think that the original template option is the most general as it would work with any future reference datasets.
