### ISSUE TITLE
ERROR: Reference and Main panels are not well aligned

### ISSUE THREAD

**Issue by dlippold** [pgxcentre/genipe#50]
I installed and tested genipe as described in the documentation on http://pgxcentre.github.io/genipe/installation.html and executed `genipe_tutorial`. I modified the generated script `execute.sh` slightly to only impute chromosome 1. After I run the script I found the following messages in the files `genipe_tutorial/genipe/chr1/chr1.alignments.log` and `genipe_tutorial/genipe/chr1/chr1.to_exclude.alignments.log`: 
> ERROR: Reference and Main panels are not well aligned:
>   * #Missing sites in reference panel = 443
>   * #Misaligned sites between panels = 56
>   * #Multiple alignments between panels = 0

In detail I did the following:

 - Installed genipe and tested the installation
 - Executed the following commands
> cd
> wget http://statgen.org/wp-content/uploads/Softwares/genipe/supp_files/hg19.tar.bz2
> wget https://mathgen.stats.ox.ac.uk/impute/1000GP_Phase3.tgz
>
> mkdir $HOME/genipe_tutorial
>
> mkdir $HOME/genipe_tutorial/hg19
> cd $HOME/genipe_tutorial/hg19
> tar -jxf $HOME/hg19.tar.bz2
>
> cd $HOME/genipe_tutorial
> tar -zxf $HOME/1000GP_Phase3.tgz
> touch 1000GP_Phase3/genipe_tut_done
>
> cd
> source genipe_pyvenv/bin/activate
> genipe-tutorial
> deactivate

In `genipe_tutorial/execute.sh` I did the following change:

 - Replaced `--chrom autosomes` by `--chrom 1` (to impute only the SNPs on the first chromosome for a test)

To speedup the test you can also do the following:

 - After the line with `--thread` add a line with `--shapeit-thread 4 \` (if your system has 4 cores)

Then I did the imputation and output the files named above:
> source genipe_pyvenv/bin/activate
> genipe_tutorial/execute.sh
> deactivate
>
> cat genipe_tutorial/genipe/chr1/chr1.alignments.log
> cat genipe_tutorial/genipe/chr1/chr1.to_exclude.alignments.log

The error messages are at the end of these files.

This error was already reported in issue #48 but that was mainly about another problem (which is resolved now).

**Comment by lemieuxl** [comment]
These are unimportant error messages. There are steps used to check the strands of the markers (*i.e.* check the alignment of the source dataset with the imputation reference files).

The first step checks the alignment and creates the files `chr*.alignments.*`. Then, using those files, we flip the markers with alignment problems and recheck the alignment (creating the files `chr*.to_exclude.alignments.*`. The markers found to have alignment problems are then excluded from the source dataset.

Those "error" messages should not appear in the phasing steps (files `chr*.final.phased.log`).
