### ISSUE TITLE
Error when --shapeit-extra '--force'

### ISSUE THREAD

**Issue by dgarrimar** [pgxcentre/genipe#55]
Hi, 

Congratulations for the great tool! I am running `genipe` in my own dataset. I filter out individuals with (>10%) missing genotypes before running it, to prevent SHAPEIT2 from erroring (in `*.final.phased.log`):

```
ERROR: 25 individuals with high rates of missing data (>10%). These individuals should be removed. You can disable this error with --force (at your own risk).
```

However, I would like to compare these imputation results with those corresponding to the non-filtered individuals. To do so, as suggested by SHAPEIT, I wanted to add the `--force` option. I tried `--shapeit-extra '--force'`. However, `genipe` complains: 

```genipe-launcher: error: argument --shapeit-extra: expected one argument```

Any hint about how to solve this?

Thanks

**Comment by lemieuxl** [comment]
Python's `argparse` sees `'--force'` as another option for *genipe* (which doesn't exist).

Try using this instead: `--shapeit-extra='--force'`.

**Comment by dgarrimar** [comment]
Great! seems to work now. Thanks a lot!
